# Binary Event Meta-Analysis Data Generating Functions

# pCFixed ---------------------------------------------------------------------- 
#   Pateras et al
pCfixedGenerateMAData <- function(theta, 
                                  k, 
                                  tau2, 
                                  p_ic_init,
                                  min_n, 
                                  max_n, 
                                  balanced = FALSE) {
  
  # Values based on quantiles from data sets generated by pRandom
  if (p_ic_init == 0.01) {
    p_ic_min <- 0.0051  
    p_ic_max <- 0.0222
  } else if (p_ic_init == 0.05) {
    p_ic_min <- 0.0257  
    p_ic_max <- 0.1046
  } else if (p_ic_init == 0.1) {
    p_ic_min <- 0.0527  
    p_ic_max <- 0.1956
  } else {
    stop("Invalid p_ic_init")
  }
  
  # 2 & 3
  if (balanced) {
    n_i <- round(runif(k, min = min_n, max = max_n))
    n_it <- n_i
    n_ic <- n_i
  } else {
    n_it <- round(runif(k, min = min_n, max = max_n))
    n_ic <- round(runif(k, min = min_n, max = max_n))
  }
  
  # 4
  theta_i <- rnorm(n = k, mean = theta, sd = sqrt(tau2))
  
  # 5
  p_ic <- runif(k, min = p_ic_min, max = p_ic_max)
  
  # 6
  p_it <- p_ic * exp(theta_i) / (1 - p_ic + p_ic * exp(theta_i))
  
  # 7
  r_ic <- rbinom(n = k, size = n_ic, prob = p_ic)
  r_it <- rbinom(n = k, size = n_it, prob = p_it)
  
  # (1) Make sure there are at least two studies with no zeros (due to the zero 
  #     exclusion CC and us needing to have at least two studies to pool)
  # (2) Make sure there is at least one zero event or non-event (otherwise no 
  #     point in even considering using a continuity correction) 
  while(sum(rowSums(cbind(r_ic, r_it) > 0) == 2) < 2 |
        ((sum(r_ic == 0) == 0 &
          sum(r_it == 0) == 0 & 
          sum(n_ic - r_ic == 0) == 0 &
          sum(n_it - r_it == 0) == 0))) {
    r_ic <- rbinom(n = k, size = n_ic, prob = p_ic)
    r_it <- rbinom(n = k, size = n_it, prob = p_it)
  }
  
  dataset <- list("TRT_event" = r_it, 
                  "TRT_n" = n_it,
                  "CTRL_event" = r_ic,
                  "CTRL_n" = n_ic)
  return(dataset)
}

# pRandomB --------------------------------------------------------------------- 
#   Bhaumik et al
pRandomBGenerateMAData <- function(theta, 
                                   k, 
                                   p_ic_init,
                                   var_mu = 0.5, 
                                   tau2, 
                                   min_n, 
                                   max_n,
                                   balanced = FALSE) {
  
  # 1 Get mu from p_ic_init
  mu <- log(p_ic_init / (1 - p_ic_init)) 
  
  # 2 
  if (balanced) {
    n_i <- round(runif(k, min = min_n, max = max_n))
    n_it <- n_i
    n_ic <- n_i
  } else {
    n_it <- round(runif(k, min = min_n, max = max_n))
    n_ic <- round(runif(k, min = min_n, max = max_n))
  }
  
  # 3 
  var_mu_esp1 <- rnorm(k, mean = 0, sd = sqrt(var_mu))
  var_theta_esp2 <- rnorm(k, mean = 0, sd = sqrt(tau2))
  
  # 4 
  p_ic <- exp(mu + var_mu_esp1) / (1 + exp(mu + var_mu_esp1))
  p_it <- exp(mu + var_mu_esp1 + theta + var_theta_esp2) /
    (1 + exp(mu + var_mu_esp1 + theta + var_theta_esp2))
  
  # 5 
  r_it <- rbinom(n = k, size = n_it, prob = p_it)
  r_ic <- rbinom(n = k, size = n_ic, prob = p_ic)
  
  # (1) Make sure there are at least two studies with no zeros (due to the zero 
  #     exclusion CC and us needing to have at least two studies to pool)
  # (2) Make sure there is at least one zero event or non-event (otherwise no 
  #     point in even considering using a continuity correction) 
  while(sum(rowSums(cbind(r_ic, r_it) > 0) == 2) < 2 |
        ((sum(r_ic == 0) == 0 &
          sum(r_it == 0) == 0 & 
          sum(n_ic - r_ic == 0) == 0 &
          sum(n_it - r_it == 0) == 0))) {
    r_ic <- rbinom(n = k, size = n_ic, prob = p_ic)
    r_it <- rbinom(n = k, size = n_it, prob = p_it)
  }
  
  dataset <- list("TRT_event" = r_it, 
                  "TRT_n" = n_it,
                  "CTRL_event" = r_ic, 
                  "CTRL_n" = n_ic)
  return(dataset)
}